### ISSUE TITLE
Failed to start the app - Migrations have failed validation

### ISSUE THREAD

**Issue by himura95** [Snd-R/komf#10]
Hello,

I reset my installation and I failed to start Komf :(

Komga version : release 0.157.0
Komf version : release 0.4.4

Launch method : java -jar komf.jar application.yml

Logs:
c:\Komga>java -jar komf.jar application.yml
16:20:13.091 [main] INFO org.flywaydb.core.internal.license.VersionPrinter - Flyway Community Edition 8.5.10 by Redgate
16:20:13.093 [main] INFO org.flywaydb.core.internal.license.VersionPrinter - See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#8.5.10
16:20:13.097 [main] INFO org.flywaydb.core.internal.license.VersionPrinter -
16:20:13.266 [main] INFO org.flywaydb.core.internal.database.base.BaseDatabaseType - Database: jdbc:sqlite:C:\Users\himura95\.komga\database.sqlite (SQLite 3.36)
16:20:13.304 [main] ERROR org.snd.Application - Failed to start the app
org.flywaydb.core.api.exception.FlywayValidateException: Validate failed: Migrations have failed validation
Detected resolved migration not applied to database: 1.
To ignore this migration, set -ignoreIgnoredMigrations=true. To allow executing this migration, set -outOfOrder=true.
Detected resolved migration not applied to database: 2.
To ignore this migration, set -ignoreIgnoredMigrations=true. To allow executing this migration, set -outOfOrder=true.
Detected resolved migration not applied to database: 3.
To ignore this migration, set -ignoreIgnoredMigrations=true. To allow executing this migration, set -outOfOrder=true.
Need more flexibility with validation rules? Learn more: https://rd.gt/3AbJUZE
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:130)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:124)
        at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:205)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:124)
        at org.snd.ApplicationKt.applyMigrations(Application.kt:40)
        at org.snd.ApplicationKt.main(Application.kt:26)

I can start Komf If I compile with .outOfOrder(true) in Application.kt but It's not a solution if I want to stay update with coming version.

Have you an Idea ?

**Comment by Snd-R** [comment]
Hey, this usually shouldn't happen. Can you post log from the start of the application? And it'll also be useful to see the contents of `flyway_schema_history` table from you database

**Comment by Snd-R** [comment]
Looks like your database has migrations from komga. Komf should be the only application modifying the database. It seems that at some point komga applied its own migrations to this database. 

You can just delete db file and start with fresh db. The only downside will be that if you had thumbnails uploaded by komf there will be duplicates on future matches for these series.
Or, if you know how, you could also copy data of old database from `MATCHED_BOOKS` and `MATCHED_SERIES` to the new database

**Comment by Snd-R** [comment]
Komf should have its own database file separate from komga database

**Comment by himura95** [comment]
I already delete database, it's a fresh install.

In application.yml , I have : 

'database:
  file: C:\Users\himura95\.komga\database.sqlite
'

It need to point to komga db or a new one ?

**Comment by Snd-R** [comment]
Yes, It should be a new file. You can call it anything for example `komf.sqlite` or you can also create a separate directory for komf config and database

**Comment by himura95** [comment]
Thanks a lot ! It work :)
