### ISSUE TITLE
Books ordered by Komf automatically resets in Komga after sometime

### ISSUE THREAD

**Issue by garvongithub** [Snd-R/komf#100]
As the title says. I don't know what causes it or is this some error but what happens is Komf order my books correctly and then later after 2 or 3 days I go to tachiyomi or komga to read it and see order is messed up. The funny thing is I am sure that komf sorted them out because I always check those series after adding them but now It's sorted out alphabetically like Komga does them. To solve it, I have to go my server and identify it again. I think locking the number and sort number fields may solve this problem.

![image](https://github.com/Snd-R/komf/assets/77321589/388c8ef2-8a36-4edf-ac76-46a0eb5bc05b)
I remember this was correctly sorted but today it is like this.

![image](https://github.com/Snd-R/komf/assets/77321589/46be707d-4d3d-40c3-9368-caf50401247a)
This too. I remember reading it as 40 but again later the order was removed automatically.

**Comment by applesoff** [comment]
I don't have all mine reset, but i do get files that arent names correctly. in my case, the volumes precede the chapters. If i have volumes 1-50 then a new chapter (ch. 150) will automatically be named #51 between vol 50 and chapter 700 for instance. i can run a manual scan after that and it will jump to where it is supposed to be though. Is there a way to automatically have komf do this?
![Screenshot 2023-09-22 at 7 23 00 AM](https://github.com/Snd-R/komf/assets/72587599/3167d595-3b59-493a-af75-d6da8addbc9e)

**Comment by garvongithub** [comment]
@applesoff  From the webui if u use user script Komf Settings→Komga→Enable Event Listener. But as I said this ordered books resets randomly so keep that in mind.
