### ISSUE TITLE
Komf docker settup troubles

### ISSUE THREAD

**Issue by BitterSweetcandyshop** [Snd-R/komf#101]
I'm not great at docker and usually run everything native, and I seem to have hit a brick wall due to not understanding how docker's networks feature completely works.

Every time I run `docker logs komf` I get similar to, despite all the variations I've tried, and eventually got to the point of just blind guessing and confusion. It's always the very first thing in the log.:
```
02:25:37.200 [OkHttp http://komga:25600/...] ERROR org.snd.mediaserver.komga.KomgaEventListener -- komga: Temporary failure in name resolution null response code null
```

Here's the command I ran to settup komga:
```
docker create   --name=Komga   --user 1000:1000   -p 2037:25600 --mount type=bind,source=/home/bittersweet/.config/Komga,target=/config --mount type=bind,source=/home/bittersweet/media/Comics,target=/Comics --mount type=bind,source=/home/bittersweet/media/Manga,target=/Manga --restart unless-stopped  -e SERVER_SERVLET_CONTEXT_PATH="/komga" gotson/komga
```

I'm unsure if I need the `/komga` in my uri due to setting it in the Komga startup or not, and if http://komga should be http://localhost or even the subnet I see docker's network runs on after using the `docker network inspect my_network` command.

I just know nothing about docker networks, and yes I bothered to google it and learning a little. I would appreciate a answer and maybe a clear explanation of how it works? like is the docker network using the 25600 port the program internally uses or would it be using the user-defined port 2037

Update: I have it like seem like it's working but not working, instead of doing it all locally I had to make komf reach out to komga via my "domain.com/komga" after that, I added some manga to komga and did a scan to see if komf would pick up on it. Nothing happened :(, I check the docker logs and I have a lot of errors like so, unsure what's causing them.
```
04:55:21.516 [OkHttp https://server.com/...] ERROR org.snd.mediaserver.komga.KomgaEventListener -- stream was reset: CANCEL null response code 200
okhttp3.internal.http2.StreamResetException: stream was reset: CANCEL
```

Later on I chose to attempt the user script, it's just port-forwarding :8001, http requests are all failing due to `Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://IP:PORT/komga/match/library/libraries/series/0DQQHVJ6S582P. (Reason: CORS request did not succeed). Status code: (null).` I tried quite a few variations.

I'm stressed so imma throw in the towel for now, thought this would be simple since I've done basic docker containers before and have OK nginx knowledge, but seems I'm just out of my depth. I suppose this is the issue with doing subfolders instead of subdomains for my server.

Note: I'm assuming that the issue has todo with the komf api being domain.com/komga and also having my komga hosted at domain.com/komga, perhaps some subfolder support would be nice, or making everything reside under a /komf subfolder by default?

**Comment by Snd-R** [comment]
check the readme section about docker create https://github.com/Snd-R/komf#running-with-docker-create

**Comment by Snd-R** [comment]
>I just know nothing about docker networks

Docker creates an isolated network for containers with each container assigned a separate ip address
And it also has an  internal dns service that containers first use to lookup the domain name. Containers will be assigned domain name matching their container name
If two containers are on the same network they can reach each other by using that domain name

**Comment by BitterSweetcandyshop** [comment]
That's much clearer then the docs I was attempting to read regarding docker networks, thanks for taking your time to write that up.

I did configure my dockeryml to include the trailing `/komga` and komf does connect to komga, only the komga userscripts fails it seems, still unsure as to why. I'll do some testing and update this comment once I find an answer. I'll close this for now, thanks for the help!
