### ISSUE TITLE
Komf only showing 10 results

### ISSUE THREAD

**Issue by abiud254** [Snd-R/komf#105]
There's a certain series I wish to identify but it's not showing in any results given cause it's only showing 10 results. 

Shouldn't I be able to see more than 10 if I am to find a specific series?

**Comment by Snd-R** [comment]
It's intended behavior. Komf will only return 5 or 10 best matching results since usually there isn't many titles with similar names 
If you still want to fill data with komf calling [http endpoint](https://github.com/Snd-R/komf) is the only option for now
