### ISSUE TITLE
OSX Komga App + Docker Komf issues?

### ISSUE THREAD

**Issue by manchesterca** [Snd-R/komf#110]
In short, if I use Komf in Mac OSX via Java, it runs fine and without issue, but I'd rather have it setup and running in the Docker container for sanity's sake.

If I run the java app it connects and is able to pull without issue, but clearly there's a disconnect between Komf being in a container, and Komf being outside (and searching for an internal komga container at http://komga:25600). How can I connect my Komf Docker to the native OSX Komga install? 

Getting a 500 error so assume it's just this issue.

**Comment by Snd-R** [comment]
You can try the solution described here: https://docs.docker.com/desktop/networking/#i-want-to-connect-from-a-container-to-a-service-on-the-host 

Changing komga url to http://host.docker.internal:25600 should just work
