### ISSUE TITLE
Komf unlocks locked number/numberSort

### ISSUE THREAD

**Issue by kiriya-aoi** [Snd-R/komf#113]
Preface: komf is not set to order books, and no metadata providers are set to fetch the number as part of book metadata.

Versions after 0.31.4 now automatically unlock all number and numberSort fields in a series on metadata update, instead of respecting the lock on those fields (and the fact that I've chosen not to fetch any such metadata).

**Comment by kiriya-aoi** [comment]
This does not appear to be fixed, my previously-set-and-locked number/numberSort are still being unlocked.

**Comment by Snd-R** [comment]
I can't seem to reproduce it anymore. Can you give an example that unlocks fields for you?

**Comment by kiriya-aoi** [comment]
I've just had it recur with `Whoever Steals This Book v01`, and sources with book-level metadata (BookWalker and/or Yen Press). Regardless of what I have set numberSort and number to both become unlocked after komf updates the book.

This is with docker and image `sndxr/komf:0.32.0`, if that's somehow behaving differently to the jar directly.

**Comment by Eagle1337** [comment]
It's broken again, which is causing me to constantly have to redo a bunch of my series number counts
