### ISSUE TITLE
Reset Metadata (by HTTP or with User Script) Does Not Clear All Metadata Fields in ComicInfo.xml

### ISSUE THREAD

**Issue by RWoof** [Snd-R/komf#117]
Ideally removing metadata for a series would wipe all of the metadata from ComicInfo.xml in each file as well or just delete the ComicInfo.xml files in the books if ComicInfo.xml creation is enabled for that library. This might not be an issue normally if the metadata will be overwritten by new information, but in my case, the new information did not contain authors and artists, so the old author and artist metadata in the ComicInfo.xml file wasn't overwritten when adding in the new metadata with komf and I ended up with a mix of old info and new info for each book in the series.

The issue was resolved this time by using the following command-line script to search each cbz file in the affected folder (in place of /seriesfolder) for ComicInfo.xml and delete if present.

find /seriesfolder -iname '*.cbz' -exec zip -d {} ComicInfo.xml \;

After the files were gone, I used the HTTP endpoint to identify the files properly and add in the correct metadata.

If it helps, the affected series was the Asterix comic which as matching with the Asterisk manga even though I had tried to set the comic library to only use Comic Vine to match using the user script. I also tried setting all providers to exact name match but that didn't work either. I wasn't able to get Comic Vine results only until I disabled all other providers, and then I could only get the first 10 without the HTTP endpoint so in the end I had to use the HTTP method to get the right match as the one I needed was the 11th or 12th result.

**Comment by Snd-R** [comment]
There's already an undocumented query parameter `removeComicInfo` for both series and library endpoints

`http://localhost:8085/{media-server}/reset/library/{libraryId}/series/{seriesId}?removeComicInfo=true`
