### ISSUE TITLE
Do not change manually selected posters/covers when updating a series/chapter/volume.

### ISSUE THREAD

**Issue by RWoof** [Snd-R/komf#118]
I use komf to fetch posters/covers, but sometimes it picks the wrong one, or picks an English cover for a Japanese book even though the library is set to Japanese language. For the most part it works well and does help, so I'd like the ability to continue using komf to fetch covers, it should ignore posters that I've replaced manually.

Right now, if I add manual covers to an existing series, then I add a new file to the directory (new chapter or volume was released), komf will scan again and reset all the covers back to the ones it finds, undoing the manual ones I selected. Since this happens, every time I add a new chapter or volume to an existing series, I need to go back and redo all of the manually selected posters after komf overrides them and sets them back to what it originally had selected.

I had posted this issue as a komga issue, but the response from gotson was:
"Once a poster is manually selected, Komga will not change it. Which is a similar behaviour to metadata locking.
I suppose komf is not looking at the poster type and always set the new one. Instead it should check the poster source and act accordingly."

Hopefully this can help to diagnose and resolve the issue.

**Comment by RWoof** [comment]
Thinking on this, I think it would be good if komf respects locked metadata fields in komga in general, if it doesn't already. I've seen a few volumes re-numbered by komf even when the field was locked.

**Comment by Snd-R** [comment]
There's an `overrideExistingCovers` option in processing settings to not override existing covers
