### ISSUE TITLE
[Feature Request] Auto-Identify Search Title preprocessing

### ISSUE THREAD

**Issue by Eico-ccm** [Snd-R/komf#121]
Hello,

Using Komf with Komga i run into the Problem that it won't automatically match all my Series as there are brackets in some of my folder Names, which are inherited by Komga in it's Series Names.

For that reason i would like an Option to preprocess the Title Name before title matching; like with an (user customizable) regular expression or smth.
This could be used for EventListener and Auto-Identify started searches.

Desired Behaviour:
Turning Series Title "Once upon a Github (2023) [github.com]" to "Once upon a Github"

Kind Regards,
Eico

**Comment by Snd-R** [comment]
Komf already removes brackets when performing search if it didn't find a match on first attempt with full name
https://github.com/Snd-R/komf/blob/f93d6ea5109091fa26b881650e8e669c44a25c9f/src/main/kotlin/org/snd/mediaserver/MetadataService.kt#L289

I don't see many use-cases that would warrant making it configurable
