### ISSUE TITLE
"t.t0.response is undefined" when trying to used the search from the userscript.

### ISSUE THREAD

**Issue by leaderofthegooftroop** [Snd-R/komf#123]
"t.t0.response is undefined" when trying to used the search from the userscript.

**Comment by leaderofthegooftroop** [comment]
I'm not seeing the location to put the komf url in my Komga UI, the identify button shows fine

**Comment by Captainpax** [comment]
same problem

**Comment by loocool2** [comment]
If you got the userscript from the greasemonkey store or similar those are extremely outdated. I have a hunch that you not being able to find the location to put the komf url in the userscript generated ui means that you're probably on some extremely early version of the userscript.

**Comment by leaderofthegooftroop** [comment]
That was the issue exactly, thanks
