### ISSUE TITLE
[Feature Request] Aggregate Web Links for Kavita

### ISSUE THREAD

**Issue by jack-mil** [Snd-R/komf#138]
We have the ability to include a single link to the metadata providers page, based on the highest priority provider. 
Since Kavita supports any number of web links, it would be great to have every meta provider linked in the series info page. 
e.g. if using MangaUpdates as highest priority, we still get links to Anilist, MAL, Mangadex, etc as configured.
This is similar to aggregating tags.

**Comment by Snd-R** [comment]
Isn't it already working like this? It was meant to work like this from the beginning and still works for me
There might be a misconfiguratin of some sort.
In case you're writing to ComicInfo Komf does not write links to it yet. There's an issue for it #87 
Please reopen if you still have the problem
