### ISSUE TITLE
Ability to not Lock Cover Images (Kavita)

### ISSUE THREAD

**Issue by majora2007** [Snd-R/komf#140]
By default, Kavita does not refresh covers unless they are missing or the underlying file explicitly changes since the last scan. 

I noticed that Komf is setting covers and locking them, thereby, Kavita sees them as "user uploaded" and will ensure they are present in backups. This can drastically bloat user's automatic backups.

Is it possible to have an opt-in option to lock covers for Kavita so that first time users aren't inuring a ton of storage overhead? 

Note: Kavita backs up up to 10 days of backups. Diesel for example is sitting on 3.7GB for each backup.

**Comment by Snd-R** [comment]
Is there a way not to lock cover during upload? When uploading a cover it locks automatically without a choice https://www.kavitareader.com/docs/api/#/Upload
would the only option be to send another series update request to unlock cover?

**Comment by majora2007** [comment]
You're right, there isn't a good way via the current API. I'll do a bit of investigation and see if I can allow the field to be explicitly unlocked.

**Comment by GlassedSilver** [comment]
I feel this would be very related: #97

**Comment by Sonny-Crockett** [comment]
https://github.com/Kareadita/Kavita/discussions/2939 - made a request there. I guess chime in to signal boost :)

**Comment by majora2007** [comment]
I added this functionality. I changed the API to allow passing both an empty string for Url and an optional coverLocked parameter. If url is empty, cover locked will force to be false. 

This should solve this issue and bring an easier integration experience as well. I will link this when the PR goes in.
