### ISSUE TITLE
ntfy support?

### ISSUE THREAD

**Issue by RandomLegend** [Snd-R/komf#145]
Heyho,

is it on your roadmap to have some additional notification service available? Maybe ntfs or apprise?

**Comment by vodkapmp** [comment]
Komf supports webhooks, and you can use webhooks with ntfy. 
So ntfy is already supported.

**Comment by Snd-R** [comment]
I've added basic Apprise cli integration, it'll require system install of Apprise (It will be available in docker image),
you should be able to call ntfy with it

I'm not sure if I want to add Apprise-api integration yet. If you want that then it'll be better to create a separate issue for that
