### ISSUE TITLE
Inadequate URL encoding / illegal character escaping

### ISSUE THREAD

**Issue by blathers16** [Snd-R/komf#149]
Fetching metadata for series with via Manga Updates with alternate titles with illegal? characters in them fails.
I have attached the log for this, as well as a plain text copy/paste of the title with the issue from manga updated.
Let me know if you need any more info.

[komf_komf-custom-app-69bd5db87c-z49nw_komf-custom-app.log](https://github.com/user-attachments/files/15840435/komf_komf-custom-app-69bd5db87c-z49nw_komf-custom-app.log)
[worthless_blacksmith_manga_updates_jp_title.txt](https://github.com/user-attachments/files/15840436/worthless_blacksmith_manga_updates_jp_title.txt)

**Comment by Snd-R** [comment]
Seems like Komga does not accept non url encoded query params in links. In this case MangaDex had this link that wasn't properly encoded. 
`https://www.cdjapan.co.jp/searchuni?fq.category=UD:14&q=不遇職『鍛冶師』だけど最強です　～気づけば何でも作れるようになっていた男ののんびりスローライフ～&order=reldesc`

**Comment by blathers16** [comment]
@Snd-R, could you please cut a release for this? I have run into a few more errors that might be related to this or something else, and I would like to rule this out before filing another bug. Also, I still can't update this series.

**Comment by Snd-R** [comment]
released in https://github.com/Snd-R/komf/releases/tag/0.34.2
