### ISSUE TITLE
Feature Request - Telegram notifications

### ISSUE THREAD

**Issue by ggoraa** [Snd-R/komf#156]
Just started using komf, and while configuring I noticed that it doesn't have Telegram support for notifications. Are there any plans to add support for it?
I can probably even do that shi myself, but beware, last time I used Kotlin was in the 1.4 days, I don't know jack about the newer versions, but still

**Comment by Snd-R** [comment]
I've added [apprise](https://github.com/caronc/apprise) integration in #145. Apprise supports telegram among other things
It'll be available in 1.0.0 release in the near future

**Comment by ggoraa** [comment]
oh damn
thx, didn't know that
