### ISSUE TITLE
Does komf update chapter covers?

### ISSUE THREAD

**Issue by tomerh2001** [Snd-R/komf#167]
I managed to get komf to update the metadata, but chapter covers are still the same - is this within the scope of komf?
<img width="1202" alt="image" src="https://github.com/user-attachments/assets/ebd6fe44-b870-4834-b87b-47f1dcf7898e">
<img width="1202" alt="image" src="https://github.com/user-attachments/assets/9fb4f4f7-b695-4c9f-8e64-e52f71e42c41">
<img width="1202" alt="image" src="https://github.com/user-attachments/assets/a3ce9a72-179d-42bb-b6ff-beff8202e927">
<img width="1202" alt="image" src="https://github.com/user-attachments/assets/d6a8a84e-7044-4ff3-9467-9bb7fe5c14b4">

I'm a bit overwhelmed by the setup; I'm not sure how I am even supposed to check if something broke or where I can see what features Komf supports/doesn't support.

**Comment by Snd-R** [comment]
At the moment Komf can only detect volumes and not chapters

Take for example bookwalker series https://global.bookwalker.jp/series/113007/ If you go to any volume page you'll see what information Komf can take. usually Komf will try to take all the available information from the provider

**Comment by tomerh2001** [comment]
> At the moment Komf can only detect volumes and not chapters
> 
> Take for example bookwalker series https://global.bookwalker.jp/series/113007/ If you go to any volume page you'll see what information Komf can take. usually Komf will try to take all the available information from the provider

Thanks for the reply!

I'm currently using Kaizoku, is there any suggested alternative to download by volumes and not chapters?

Non of my manga has volumes, so I'm assuming it's something with the way I get it?

**Comment by vodkapmp** [comment]
> > At the moment Komf can only detect volumes and not chapters
> > Take for example bookwalker series https://global.bookwalker.jp/series/113007/ If you go to any volume page you'll see what information Komf can take. usually Komf will try to take all the available information from the provider
> 
> Thanks for the reply!
> 
> I'm currently using Kaizoku, is there any suggested alternative to download by volumes and not chapters?
> 
> Non of my manga has volumes, so I'm assuming it's something with the way I get it?

Basically none of the online reading sites that software like Kaizoku scrapes does per volume releases.

You'd have to either buy from somewhere like Amazon and rip them to your library yourself, or get them from other sources online.
You could also manually combine your per-chapter files into volumes by finding the chapter count per volume etc, but kaizoku would then download the missing chapters that you suddenly don't have anymore.
