### ISSUE TITLE
Feature request: Auto ordering volumes + chapters in same folder

### ISSUE THREAD

**Issue by johanderohan** [Snd-R/komf#17]
Hello, I created a script to be able to order the manga volumes and chapters in a single directory to keep the reading order. Works very well with English releases.

My script was made fast and it's a bit messy, but now that komf adds metadata for each volume of the series, maybe the “order” and “sort order” fields could be modified at the time metadata is added.

Komf should reorder series every time is updated because new volumes maybe added (and should be at first position) and ignore if the metadata fields are locked. 

I added a Metadata refresh to update cover if order changes but not sure if is the best option.

I leave my script here in case it helps, although I already say, it is quite dirty…

https://gistcdn.githack.com/johanderohan/4782b277e708768bb24e453a1dc05542/raw/e8cfaa769e7330f9544f99916943912cccde1b27/komga-autoorder.v1.0.js

<img width="1169" alt="Captura de pantalla 2022-10-30 a las 19 11 24" src="https://user-images.githubusercontent.com/5054607/198894538-20f61ce3-4cb0-486d-98ef-8b2a59486d47.png">

**Comment by Snd-R** [comment]
I'm not sure if this should be added. There's already quite a number of config options but it certainly can be added
And with your approach it would be impossible to handle cases with mixed volumes in between the chapters although i doubt anyone will be in that situation

To me it seems like it'd be a better solution to name your files in alphabetical order for example:
`Dandadan - c001-005x1 (v01) [dig] [VIZ Media].cbz`
`Dandadan - c006 [web] [VIZ Media].cbz`
...
That way even simple readers and other programs will be able to read all files in correct order

**Comment by applesoff** [comment]
I have settled on doing this with a naming structure involving something such as Dandadan - v01 followed by Dandadan Chapter 006. This way the volumes are always first. The only issue I have run into is with series that name chapters with #006. Otherwise this has worked beautifully.

**Comment by johanderohan** [comment]
Hello, I understand the point of view. I think that the fewer modifications made to the original files, the better for everyone.

When they are renamed, they are files that can no longer be "shared", and also require more previous work from the "library manager".

My personal opinion is that filenames should never be changed.

This is the Plex way. There are several naming conventions for tv shows but regardless of the name of the file Plex is able to parse it and order the chapters at metadata level.

For example, i can have two different versión of the series in the same folder (different language):

`House of dragon S01E02`
`La casa del dragon 1x01 (Spanish version)`
...

And Plex will order it right.

I don't know how users are currently managing their libraries, but may be your are right and this kind of functionality requires some more discussion.

Thank you very much!
