### ISSUE TITLE
Error fail to fetch, please help me.

### ISSUE THREAD

**Issue by flamesky80** [Snd-R/komf#173]
1、Installed komf with docker
2、Created application.yml following the guide : https://github.com/Snd-R/komf?tab=readme-ov-file#example-applicationyml-config
3、Filled in Komga's Uri user and password, enabled = true
4、Started docker, visited the komf webui, but an error showed up, and couldn't log in with Komga's user and password
![image](https://github.com/user-attachments/assets/3efd92c0-f7ef-430b-b2dd-ff384a2966da)
5、However, in komf-userscript UI, it showed as connected
![image](https://github.com/user-attachments/assets/40acba24-a019-463b-a2bf-81d3db0eade5)

6、Then I try to follow the tip in Komf login UI
![image](https://github.com/user-attachments/assets/ae2df703-c558-4f36-a72c-f1cdb3e9d5af)
7、Created application.yml following the guide: https://komga.org/docs/installation/configuration/#komga_cors_allowed_origins--komgacorsallowed-origins-origins
8、Filled in the url:port of komf
![image](https://github.com/user-attachments/assets/915700f1-e11a-4202-aefb-8197439051ef)
9、Restarted the docker of Komga, and an new issue showed, I couldn't visit the webui of Komga now
![image](https://github.com/user-attachments/assets/891cc94f-8ee7-43f8-ad38-3b5d24fb4128)
10、Here is the log of Komga container console:
> 2024-10-16T04:18:25.807Z  INFO 1 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 18 endpoint(s) beneath base path '/actuator'
> 2024-10-16T04:18:26.000Z  INFO 1 --- [           main] o.s.s.web.DefaultSecurityFilterChain     : Will secure Or [Mvc [pattern='/api/**'], Mvc [pattern='/opds/**'], Mvc [pattern='/sse/**'], Mvc [pattern='/oauth2/authorization/**'], Mvc [pattern='/login/oauth2/code/**'], EndpointRequestMatcher includes=[*], excludes=[], includeLinks=true] with [org.springframework.security.web.session.DisableEncodeUrlFilter@6070990b, org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@64b7066e, org.springframework.security.web.context.SecurityContextHolderFilter@2138386f, org.springframework.security.web.header.HeaderWriterFilter@541ea657, org.springframework.web.filter.CorsFilter@79b9b628, org.springframework.security.web.authentication.logout.LogoutFilter@222af5ff, org.springframework.security.web.session.ConcurrentSessionFilter@2f2e75ae, org.springframework.security.web.authentication.www.BasicAuthenticationFilter@519b726a, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@5146ae5e, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@642270ad, org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter@1d691d4f, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@7f5582db, org.springframework.security.web.session.SessionManagementFilter@4602fa2f, org.springframework.security.web.access.ExceptionTranslationFilter@5963a2c9, org.springframework.security.web.access.intercept.AuthorizationFilter@788be73c]
> 2024-10-16T04:18:26.039Z  INFO 1 --- [           main] o.s.s.web.DefaultSecurityFilterChain     : Will secure Or [Mvc [pattern='/kobo/**']] with [org.springframework.security.web.session.DisableEncodeUrlFilter@46219104, org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@64c009b8, org.springframework.security.web.context.SecurityContextHolderFilter@7859bd9a, org.springframework.security.web.header.HeaderWriterFilter@22a9fa23, org.springframework.web.filter.CorsFilter@77510da, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@4ad0465c, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@561e8bab, org.gotson.komga.infrastructure.security.apikey.ApiKeyAuthenticationFilter@570f96b7, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@1dec84e3, org.springframework.security.web.access.ExceptionTranslationFilter@2a3de2b, org.springframework.security.web.access.intercept.AuthorizationFilter@e8bd42f]
> 2024-10-16T04:18:26.973Z  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port 25600 (http) with context path '/komga'
> 2024-10-16T04:18:27.032Z  INFO 1 --- [           main] org.gotson.komga.ApplicationKt           : Started ApplicationKt in 20.789 seconds (process running for 21.93)
> 2024-10-16T04:18:27.135Z  INFO 1 --- [         task-8] g.k.i.s.ThumbnailMetadataFixerController : Find and fix thumbnails without metadata
> 2024-10-16T04:18:27.169Z  INFO 1 --- [         task-8] o.g.komga.application.tasks.TaskEmitter  : Sending task: FixThumbnailsWithoutMetadata(priority='0')
> 2024-10-16T04:18:27.267Z  INFO 1 --- [   scheduling-1] .AuthenticationActivityCleanupController : Remove authentication activity older than 2024-09-16T04:18:27.263432477 (UTC)
> 2024-10-16T04:18:27.460Z  INFO 1 --- [         task-1] o.g.k.i.scheduler.SearchIndexController  : Lucene index version: 8
> 2024-10-16T04:18:27.643Z  INFO 1 --- [taskProcessor-1] o.g.komga.application.tasks.TaskHandler  : Executing task: FixThumbnailsWithoutMetadata(priority='0')
> 2024-10-16T04:18:27.680Z  INFO 1 --- [taskProcessor-1] o.g.k.domain.service.ThumbnailLifecycle  : Fetched 0 ThumbnailBook to fix, total: 0
> 2024-10-16T04:18:27.689Z  INFO 1 --- [taskProcessor-1] o.g.k.domain.service.ThumbnailLifecycle  : Fixed 0 ThumbnailBook in 37.306369ms
> 2024-10-16T04:18:27.696Z  INFO 1 --- [taskProcessor-1] o.g.k.domain.service.ThumbnailLifecycle  : Fetched 0 ThumbnailSeries to fix, total: 0
> 2024-10-16T04:18:27.697Z  INFO 1 --- [taskProcessor-1] o.g.k.domain.service.ThumbnailLifecycle  : Fixed 0 ThumbnailSeries in 6.502017ms
> 2024-10-16T04:18:27.704Z  INFO 1 --- [taskProcessor-1] o.g.k.domain.service.ThumbnailLifecycle  : Fetched 0 ThumbnailSeriesCollection to fix, total: 0
> 2024-10-16T04:18:27.715Z  INFO 1 --- [taskProcessor-1] o.g.k.domain.service.ThumbnailLifecycle  : Fixed 0 ThumbnailSeriesCollection in 6.918371ms
> 2024-10-16T04:18:27.722Z  INFO 1 --- [taskProcessor-1] o.g.k.domain.service.ThumbnailLifecycle  : Fetched 0 ThumbnailReadList to fix, total: 0
> 2024-10-16T04:18:27.723Z  INFO 1 --- [taskProcessor-1] o.g.k.domain.service.ThumbnailLifecycle  : Fixed 0 ThumbnailReadList in 6.348329ms
> 2024-10-16T04:18:27.724Z  INFO 1 --- [taskProcessor-1] o.g.komga.application.tasks.TaskHandler  : Task FixThumbnailsWithoutMetadata(priority='0') executed in 78.409424ms

**Comment by Snd-R** [comment]
>Tomcat started on port 25600 (http) with context path '/komga'

you have context path configured somewhere. You'll be able to access komga with http://locahost:25600/komga
if you don't want it then remove it from your config

**Comment by flamesky80** [comment]
> > Tomcat started on port 25600 (http) with context path '/komga'
> 
> you have context path configured somewhere. You'll be able to access komga with http://locahost:25600/komga if you don't want it then remove it from your config

I installed Komga correctly and accessed the webui at http://192.168.2.199:13414.
Port 13414 is mapped to port 25600 inside the container.
Since the application.yml file was created for Komga, no matter whether I set the port to 13414, 25600, or even delete it in the file, I can't access Komga's webui anymore.

**Comment by flamesky80** [comment]
The 'application.yml' file I mentioned is not the one needed by Komf, but the one required by Komga CORS.

**Comment by Snd-R** [comment]
Yes, I mean your komga application.yml file probably contains context-path option which maps the path you access komga to `http://baseuri/komga`
If you copied example config from komga doc page you'll need to remove this line
![image](https://github.com/user-attachments/assets/9330832a-1a38-43c4-99de-0665ce7ca539)

**Comment by flamesky80** [comment]
> Yes, I mean your komga application.yml file probably contains context-path option which maps the path you access komga to `http://baseuri/komga` If you copied example config from komga doc page you'll need to remove this line 

Thanks very much, it works !
By the way, what's the difference between 'http://localhost:25600' and 'http://localhost:25600/komga' ?
