### ISSUE TITLE
Feature request: Allow option to chose series title if provider has multiple ones

### ISSUE THREAD

**Issue by MEGAMENE** [Snd-R/komf#18]
Hi, I've recently installed Komf and it's working pretty good for the most part.

I've chosen to use the AniList metadata provide, and I noticed that some series were getting their official English title instead of the Romaji one, even though AniList shows the Romaji one as the main series title.

I looked at the code and saw that the Romaji title was only used if there wasn't an English one. An option to choose the preferred title on the application.yml would be greatly appreciated.

**Comment by Snd-R** [comment]
Some providers don't differentiate between title types like mangaupdates. 
It might be possible to add a config option flag to choose title type and only update title if provider has this title type

**Comment by MEGAMENE** [comment]
> Some providers don't differentiate between title types like mangaupdates. It might be possible to add a config option flag to choose title type and only update title if provider has this title type

I thought about that problem. would it make sense to add providers specific settings?
