### ISSUE TITLE
[Feature request] A list of characters that produce errors

### ISSUE THREAD

**Issue by LavaLaugh** [Snd-R/komf#191]
Some characters in filenames give the error: java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters

It would be nice to know which characters can't be used so we can change the filenames accordingly.

**Comment by LavaLaugh** [comment]
At the moment, I have only gotten this issue with the é character.

**Comment by Snd-R** [comment]
How are you running komf? jar, docker? and what's your OS?
If you're on Linux and running jar file, you can add `LC_ALL=en_US.UTF-8` env variable before the command `LC_ALL=en_US.UTF-8 java -jar komf.jar`

**Comment by LavaLaugh** [comment]
Thanks for the tip! It helped me get on the right track.

I am running Komf in a Proxmox LXC container and I just realized that LXC containers get the "C" locale as standard and not the a UTF-8 locale.

The fix was to execute a _dpkg-reconfigure locales_ and after a reboot, everything worked as needed.

**Comment by LavaLaugh** [comment]
Fixed my problem
