### ISSUE TITLE
[Nautiljon] Enhancement : Pick French publisher over Japanease one

### ISSUE THREAD

**Issue by sam5558** [Snd-R/komf#2]
Hello @Snd-R ,
Taking into consideration that people searching for french metadata fetch will most likely possess french translated manga, i tought it would make sense if you could pick French publishers over japanease ones.
I've discussed with Gotson (creator of Komga) on having both publishers but he believes it should be unique (or create another tag for other publishers).
eg : Choosing Pika over Kodansha here
![Screenshot_20220401_204921](https://user-images.githubusercontent.com/26897744/161339644-27feb929-708b-4959-9933-9736c05ebd93.png)
 
Thank you for your hard work

**Comment by Snd-R** [comment]
Added configuration options for original and french publishers as well as an option to add custom tag for both publishers.
See example config for details
