### ISSUE TITLE
Remember last metadata provider for future scans

### ISSUE THREAD

**Issue by applesoff** [Snd-R/komf#21]
Currently komf picks up metadata when new books are added to a library or a scan is manually initiated and will use closest match or exact matching based on file name. If set to exact, many series do not get picked up and if using closest match the series may grab another closely named series (i.e. matching A Certain Scientific Accelerator to A Certain Scientific Railgun).

If there was a way to have komf use the latest ID match (wether manually or automatically) to match future scans when books are added it would save the user from needing to manually scan improperly matched sources.

**Comment by Snd-R** [comment]
Komf will now remember provider and series from your last manual identification
Auto-identification results will not be remembered
