### ISSUE TITLE
Metadata providers for manhwa and webtoons

### ISSUE THREAD

**Issue by applesoff** [Snd-R/komf#22]
There are many popular manhwa and webtoons that have very limited metadata on anilist, mangaupdates and MAL. Adding official (?) or more robust metadata providers for these types of content would be great.

**Comment by lambdareader** [comment]
afaik official providers usually have less metadata than MU. MU usually is best, but anime-planet could be an option, their collection is reasonably full and their thumbnails have a much higher resolution than MU.

**Comment by Kpalaz** [comment]
Mangadex or Anime-planet seem to be the only decent sources for OEL currently.

**Comment by Snd-R** [comment]
closed in favor of #86
