### ISSUE TITLE
Feature request: Option to filter names before searching / Change auto identification name to title

### ISSUE THREAD

**Issue by lambdareader** [Snd-R/komf#26]
Some directory names are 'Manganame (2022) (Digital) (Groupname)' and renaming them is not an option. Kavita automatically filters all names so only 'Manganame' remains.
Komga doesn't do that the name of the series is 'Manganame (2022) (Digital) (Groupname)', so an option in application.yml would be appreciated.
Simply allowing everything in parenthesis to be excluded from search would be enough, since most automatic identifications don't work currently.

Edit: I used the Komga API to rename all series but it was useless since komf uses 'name' and not 'title'. That should be changed. The name can only be changed if you change the directory name. Title can be changed in webui and API. It is the same as name except if you manually change it. So it shouldn't break anything for users. (interestingly enough the userscript uses title when manually identifying)
Please change the source from name to title.

**Comment by Snd-R** [comment]
I suppose it makes more sense to use series title and not folder name
It's also possible to remove parenthesis on komf side when launching a search

**Comment by Snd-R** [comment]
Handling series name filters would require complicated regex matches to account for all edge cases
I think it's better to leave this either to user or media server to properly set series name
I've decided to just use series metadata title from komga or kavita
