### ISSUE TITLE
Feature request: Add a swagger page

### ISSUE THREAD

**Issue by darthmooguy** [Snd-R/komf#3]
Since this project is API only, I think it would be neat to have a swagger page with the endpoints, so we can call them without needing postman or curl!

See the following documentation on Swagger/OpenApi for javalin: https://javalin.io/plugins/openapi

It could serve as documentation as well as a way to easily call the endpoints.

Let me know what you think!

I’m also on the Komga discord if you want to talk there.

**Comment by Snd-R** [comment]
I don't really want to bring this plugin as it will effectively double jar size by bringing a lot of transitive dependencies and there aren't many endpoints to justify this.
