### ISSUE TITLE
Setting DIfferent Rules for Different Libraries

### ISSUE THREAD

**Issue by CardcaptorRLH85** [Snd-R/komf#30]
I couldn't find anywhere to ask a komf question other than here.  If I need to move elsewhere, please tell me.

If it is possible to set different rules for different libraries, I haven't figured out how to do it.  For example, I have three libraries now Comics (for western comics) that I want to have default to left-to-right, Manga (for manga, manhwa, etc.) which should default to right-to-left, and Webtoons which should default to webtoon view.

If this can't be done currently then you can call this a feature request.  I _have_ figured out that I can run three copies of komf in docker each linked to a single library but running three instances feels a bit wasteful of system resources if it can be done in one.

**Comment by Snd-R** [comment]
Currently it's not possible, but it'd be a nice feature to have
