### ISSUE TITLE
[Feature Request] Per Library Filter

### ISSUE THREAD

**Issue by JShiesty-dev** [Snd-R/komf#34]
Some users separate their manga from their light novels by having two separate libraries. Some light novels have adaptations that share the same or similar name. Prior to one of the newer updates that filters OUT light novels, when I would auto-identify my light novel library, most of my light novels would get identified as manga adaptations instead of light novels. There should be some sort of line for the app config along the lines of:

```
library:
     1:
          malFilter: "manga, manhwa" # Ex. "manga" "light novel" or "manhwa" or "manga, manhwa"
     2:
          malFilter: "light novel" # Ex. "manga" "light novel" or "manhwa" or "manga, manhwa"
```

The filter should only search for the types of books specified. So if I enter "manga, manhwa" for library 1, MAL only matches the books in library 1 with the manga and manhwa types on MAL. The main idea is to make this library-specific. You should be able to set this filter based on each individual library.

**Comment by Snd-R** [comment]
I feel like a simpler more generic option would be better. That way it can uniformly be applied to other providers
e.g.
```yml
    mal:
      priority: 1
      enabled: true
      mediaType: "NOVEL" # or mediaType: "MANGA"

```

**Comment by JShiesty-dev** [comment]
Assuming your suggestion can be changed per library, that would work fine. As long as you are able to have one library be "NOVEL" and one be "MANGA" and so on, that is fine. Also, it would be great if you could have multiple. Ex. mediaType: "MANGA, MANHWA"

**Comment by Snd-R** [comment]
I still not sure about this config structure. For now it will remain like that. If you have any suggestions on how to improve it you can open another issue
