### ISSUE TITLE
It adds completed manga as ongoing

### ISSUE THREAD

**Issue by toprak** [Snd-R/komf#37]
Hi I started using komf yesterday, everything was fine, but today for some reason it's adding completed manga as ongoing.
OS: Arch Linux  komf:0.18.2 komga: 0.160.0
Running komga with systemd for all users (system-wide) (java -jar komga) , Running komf systemd as well (java -jar komf.jar --config-dir=/home/user/komf)
https://termbin.com/9fo36 application yml

**Comment by applesoff** [comment]
You can check the komf log to see where it's pulling metadata from based on your application.yml It seems like manga updates and any list are your top two. Check their sites to see if they have incorrect information about ongoing verse ended series. I've had this issue before. I try to use official sources to prevent this

**Comment by Snd-R** [comment]
Not sure what would be the right behavior for cases when mangaupdates contains both completed and ongoing volume information, to be safe I suppose it should just not return data about status
But for cases when all volume types are completed it does makes sense to mark whole series as completed

**Comment by toprak** [comment]
@Snd-R i think as u said if all volume type is completed then let komf set as completed
