### ISSUE TITLE
[Feature Request] Please add adult manga site support

### ISSUE THREAD

**Issue by xScarbo** [Snd-R/komf#46]
As someone who mainly uses Kavita to compile and read doujins, I'd love to be able to easily fetch metadata for hentai manga and incorporate them into my library, but it seems KOMF currently doesn't support adult manga sites.
Unfortunately, most doujinshi and hentai manga are not listed on the standard anime databases like MAL.
Please consider adding support for adult manga sites like nhentai.net, hitomi.la, e-hentai.org.

**Comment by edgehub-cloud** [comment]
for official , fakku.net

**Comment by eswiig** [comment]
nhentai support would be great

**Comment by schklom** [comment]
The problem with nhentai.net is that there is often a Cloudflare barrier that prevents accessing it.
Luckily, there is nhentai.xxx that is a mirror of the .net version. The downside is that it has a delay of at least a few days (I did not count precisely), so anything new takes some time to become available on the .xxx version.

**Comment by garvongithub** [comment]
Please Consider adding this, my usecase is also similar. While Anilist has some data, It is very small compared to what these above mentioned sites hold.

**Comment by Snd-R** [comment]
closed in favor of #86
