### ISSUE TITLE
Accommodate titles with special characters

### ISSUE THREAD

**Issue by loocool2** [Snd-R/komf#48]
Some entries have characters with special characters in them, like if a title has the word Café or if it's Lucky★Star. Currently, the auto matcher errors on these titles and the aggregate filters entries with titles with non ascii printable characters.

https://cdn.discordapp.com/attachments/985838635783954492/1079580606297538680/message.txt
Logs of one instance where the auto matcher error'd

**Comment by Snd-R** [comment]
Malformed input or input contains unmappable characters error can be fixed by setting LANG="en_US.UTF-8"  and LC_ALL="en_US.UTF-8" environment variable

`LANG=en_US.UTF-8  LC_ALL=en_US.UTF-8 java -jar ...`
