### ISSUE TITLE
Bangumi metadata provider (Chinese)

### ISSUE THREAD

**Issue by iveney** [Snd-R/komf#52]
First of all, thanks for working on this wonderful project :)

Wonder if anyone is interested in metadata providers in Chinese. [Bangumi](https://bgm.tv/subject/4923) is a good one. I did some poking and have something working for myself on Kavita (see screenshot for `Full Metal Alchemist`). Can tidy it up for a pull request if [this](https://github.com/iveney/komf) seems valuable. 

![image](https://user-images.githubusercontent.com/51033/230800568-ee5a0fc7-7aeb-4909-83b1-f6037f7d95ba.png)

**Comment by Snd-R** [comment]
Looks good to me. If you don't mind I can take your changes and finish the provider
