### ISSUE TITLE
[Feature Request] Allow for the Use of Native Author Names

### ISSUE THREAD

**Issue by kanjieater** [Snd-R/komf#69]
I just added this series to Komga. 
https://www.mangaupdates.com/series/iruclj2/daisan-no-kagemusha

I had the authors name set as `黒藤広隆` but komf overwrote it as(KUROFUJI Hirotaka
https://www.mangaupdates.com/author/v8lgg4m/kurofuji-hirotaka

Would it be possible to allow for native author names? I know it's available on mangaupdates (not sure via api) & anilist (definitely available via gql).

**Comment by Snd-R** [comment]
duplicate of #33
