### ISSUE TITLE
Cover art

### ISSUE THREAD

**Issue by applesoff** [Snd-R/komf#7]
Is there a way to have komf search for higher resolution covers? Some of mine are quite pixelated.

**Comment by Snd-R** [comment]
Komf chooses the cover art from whatever the first source that matches. And unfortunately mangaupdates has lower quality covers. I'll consider adding some configuration that will allow choosing cover art from other providers

**Comment by Snd-R** [comment]
With https://github.com/Snd-R/komf/releases/tag/0.8.0 you can now enable metadata aggregation from multiple sources. Enable mangaupdates and any other provider that you want covers from and disable thumbnail metadata field in mangaupdates.
