### ISSUE TITLE
Setting of artistRoles not work properly

### ISSUE THREAD

**Issue by rosystain** [Snd-R/komf#76]
I prefer to only display the artist in the "Penciller" field, so I have removed the mappings for other roles.

<img width="470" alt="image" src="https://github.com/Snd-R/komf/assets/27495128/34affd4d-4c1c-42c6-8394-f4c2e2aba191">

But when I click "SAVE," they revert back to their original appearance.

<img width="457" alt="image" src="https://github.com/Snd-R/komf/assets/27495128/7da3304e-6008-4f8f-887e-823bb818ca58">

Meanwhile, adding ```artistRoles: [ "PENCILLER" ]``` in the application.yml file doesn't seem to have any effect.

**Comment by Snd-R** [comment]
Config not saving is a userscript problem
Manually setting config works for me, make sure you set artist roles for any other provider as well

**Comment by Snd-R** [comment]
It should be fixed in latest userscript version https://github.com/Snd-R/komf-userscript/releases/tag/0.11.0

**Comment by rosystain** [comment]
Updating to the latest userscript indeed resolved the issue. Thank you!
