### ISSUE TITLE
Komf stopped working after Komga v1.0 release

### ISSUE THREAD

**Issue by eswiig** [Snd-R/komf#78]
I suspect this is due to the port change in Komga

🚨 change default port from 8080 to 25600 ([9b519e4](https://github.com/gotson/komga/commits/9b519e4))

how can we update komf to use this new port?

**Comment by Snd-R** [comment]
just change the port in komga base uri either in config `komga.baseuri=http://komga:25600` or with env var `KOMF_KOMGA_BASE_URI=http://komga:25600`

**Comment by eswiig** [comment]
I use Komga and Komf with Traefik, so I normally don't specify a port as Traefik handles it.

getting error
![image](https://github.com/Snd-R/komf/assets/58608430/6cc39085-5775-4ed4-96a1-66a0e7e8fc90)

**Comment by Snd-R** [comment]
are you running komf and komga in docker?
In userscript in connection tab you should input komf address `http://localhost:8085`
In Komga tab it should be komga address `http://komga:25600`
