### ISSUE TITLE
Western Comic Metadata Providers

### ISSUE THREAD

**Issue by CardcaptorRLH85** [Snd-R/komf#9]
Is there a chance to have any western comic metadata providers added to komf?  I have separate libraries in Komga for my manga and comics and while this is the second program I've found for updating my manga metadata, I haven't found one to handle my comic metadata.  If that's outside of the scope of this application that's fine, I'll just use this one for my manga and look for something else for my comics.

Thanks for your assistance here!

**Comment by Snd-R** [comment]
Comicvine as a source is planned to be added in the future. I'll take a look at it this weekend but I have no timeline for release date of this feature

**Comment by mayanez** [comment]
Any progress on this yet?

I'm not too familiar with Kotlin, but am happy to help. If you already have a partial implementation I can pick this up from there.

**Comment by Snd-R** [comment]
I've started working on comicvine provider. I'll try to release it in the near future
I'm also considering [metron](https://metron.cloud/) provider

**Comment by Snd-R** [comment]
closing this as comicvine provider was already added and is working
