### ISSUE TITLE
Add additional ComicVine fields 

### ISSUE THREAD

**Issue by RickSWilliams** [Snd-R/komf#90]
I'd like to see more options for what fields can be pulled from comicvine.

Two major ones that I see that currently don't get pulled, therefore don't get reflected in Komga or the Comicinfo.xml are:

Title and Series

**Comment by jnbht** [comment]
Yes please!

**Comment by wanestar** [comment]
Agree, it would be awesome. Komf works great, but with this change, it would fully replace ComicTagger for me and achieve full automation for my library.

**Comment by vodkapmp** [comment]
Would be awesome to be able to pull book/chapter titles from ComicVine.
