### ISSUE TITLE
[ENHANCEMENT] Add covers only to first chapter (book) in a volume instead of to every chapter (Kavita)

### ISSUE THREAD

**Issue by GlassedSilver** [Snd-R/komf#97]
It would be nice if Komf could add the covers for volumes rather than the chapters, since that way the volumes get cover art without taking away the ability to see a preview of chapters in the given view.

**Comment by GlassedSilver** [comment]
Any update on whether this could be implemented? I don't know if Kavita's API allows manipulating the cover art of volumes for example.

**Comment by Snd-R** [comment]
Volumes are compiled from chapters, and Kavita only allows to upload chapter covers. 
If you look at how webui handles cover uploads for volumes you'll see that it uploads cover for the first chapter in it

**Comment by GlassedSilver** [comment]
> Volumes are compiled from chapters, and Kavita only allows to upload chapter covers. If you look at how webui handles cover uploads for volumes you'll see that it uploads cover for the first chapter in it

So that explains how it would need to be implemented if someone agrees this could be a useful feature.

That being said obviously the best thing would be for cover art to be stored and accessed separately from chapter files, but that's not up to Komf. (e.g. volume01.jpg or cover_v01.webp, etc...)

**Comment by GlassedSilver** [comment]
Clarified my title since the way its technically done isn't the primary goal of this enhancement idea.

It just should be easier for chapter-based collectors and readers to see a page glimpse in chapter view rather than seeing the same cover of a given volume 10 times in a row.
That gets old pretty fast and finding a specific chapter again based on vaguely remembering the start at least turns into an odyssey.

**Comment by majora2007** [comment]
I just stumbled upon this thread. I can build an endpoint for Volumes that will do the heavy lifting for Komf. I'll mark this for the v0.8.3 release.

**Comment by GlassedSilver** [comment]
You're a true gem to the manga community! ❤️

**Comment by majora2007** [comment]
I've added this and it will be available for mainstream consumption starting with v0.8.3. Feel free to test it with the nightly and let me know of any issues.

**Comment by Snd-R** [comment]
I don't think Komf can use that endpoint at the moment. It does its own name parsing to determine what is a volume by checking each chapter's object filename. 

I'm not quite clear to what this issue here is asking for specifically.
Is it the ability to upload volume cover in addition to chapter cover? From what I understand it currently not possible to do in Kavita

If it's just to upload cover for the first chapter then Komf will need to adjust its update logic to group multiple books that are considered a volume and only update cover and metadata for the first file e.g. if you have 2 files
`series - c001 (v01).cbz` and `series - c002 (v01).cbz` it should upload covers for first file only

Currently Komf will treat both files as a volume and update the same metadata and cover for both of them

**Comment by GlassedSilver** [comment]
Yes, the latter. If you store and read chapter by chapter to have a volume's cover on every chapter means your chapter previews are completely out of whack.

Naturally I believe Kavita should treat chapter previews and volume covers as different entities altogether, but if Komf could accommodate for this and therefore any other software universally therefore that'd be great.

**Comment by majora2007** [comment]
This is what the new API allows. If you have a volume Id you can set JUST the volume cover and leave the underlying chapter cover normal.

**Comment by Snd-R** [comment]
Isn't the new endpoint just sets the cover for the first chapter? From what I see it still updates both volume and chapter covers

https://github.com/user-attachments/assets/6c6b9609-f223-4ce1-97f6-3f1ca26c56ba

**Comment by majora2007** [comment]
You're right, I just checked the code and saw I was still updating the chapter. I'll make sure it gets fixed up.
